export const ACTION_TYPES = {
    SET_NAME_REVIEW_FORM: 'SET_NAME_REVIEW_FORM',
    SET_TEXT_REVIEW_FORM: 'SET_TEXT_REVIEW_FORM',
    SET_RATING_REVIEW_FORM: 'SET_RATING_REVIEW_FORM',
    CLEAR_REVIEW_FORM: 'CLEAR_REVIEW_FORM'
}